name: generate breakout svg

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}
          # Optionally define a personal token secret named BREAKOUT_TOKEN for more reliable API calls
          github_token: ${{ secrets.BREAKOUT_TOKEN != '' && secrets.BREAKOUT_TOKEN || github.token }}

      - name: Debug output directory (pre-move)
        run: |
          echo "Listing output directory (if exists) before moving:"
          ls -al output || echo "output directory not found"
          if [ -f output/light.svg ]; then head -n 5 output/light.svg; fi
          if [ -f output/dark.svg ]; then head -n 5 output/dark.svg; fi

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg || echo "Light SVG not found"
          mv output/dark.svg images/breakout-dark.svg || echo "Dark SVG not found"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"
          git push
